version: "3"

services:
  hymncoreapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7077:7077"
      - "5019:5019"
      - "443:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:7077;http://+:5019"
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Koekje123"
      MUSIC_DIRECTORY: "/music"
    volumes:
      - ./certs:/https
      - "C:/Fontys ICT/Semester 3/IPS Individueel Project/Music:/music:ro"
    networks:
      - hymnnet

networks:
  hymnnet:
    driver: bridge
