name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/HymnMusicAPI/HymnMusicAPI.sln
    - name: Build
      run: dotnet build Backend/HymnMusicAPI/HymnMusicAPI.sln --no-restore
    - name: Test
      run: dotnet test Backend/HymnMusicAPI/HymnMusicAPI.sln --no-build --verbosity normal
